
services:
  app:
    build: ./app
    image: app:1.0.0
    container_name: app
    command: python -m bot.main
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /usr/src/app
          ignore:
            - venv/
        - action: rebuild
          path: ./app/requirements.txt
        - action: rebuild
          path: ./app/entrypoint.sh
    restart: unless-stopped #no, always, on-failure: 5, unless-stopped
    env_file:
      - ./app/.env
    depends_on:
      - db
  db:
    image: postgres:16-bookworm
    container_name: db
    volumes:
      - ./data:/var/lib/postgresql/data/
    restart: unless-stopped #no, always, on-failure: 5, unless-stopped
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=notes
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=localhost
